version: '3.8'

services:
  # Main application service
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
    depends_on:
      - phi3
    networks:
      - xai_network
    restart: unless-stopped

  # Phi-3 LLM service
  phi3:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - xai_network
    restart: unless-stopped
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "ollama serve &
      sleep 10;
      ollama pull phi3;
      wait"

  # Optional: Database backup service
  backup:
    image: alpine:latest
    volumes:
      - ./data:/data
      - ./backups:/backups
    command: >
      sh -c "
      while true; do
        if [ -f /data/loan_predictions.db ]; then
          cp /data/loan_predictions.db /backups/loan_predictions_backup_$(date +%Y%m%d_%H%M%S).db
          find /backups -name 'loan_predictions_backup_*.db' -mtime +7 -delete
        fi
        sleep 3600
      done
      "
    depends_on:
      - app
    networks:
      - xai_network
    restart: unless-stopped

networks:
  xai_network:
    driver: bridge

volumes:
  ollama_data:
  app_data: